version: "3.7"

services:
  nginx:
    image: nginx:1.21.5-alpine
    container_name: proxy
    ports:
      - 8000:80
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend

  frontend:
    build: ./frontend
    container_name: frontend
    restart: always

  backend:
    build: ./backend
    container_name: backend
    restart: always
    depends_on:
      - postgres

  postgres:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fullstack
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    ports:
      - 8888:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres


volumes:
  postgres-data:
  pgadmin-data: