version: "3.7"

services:
  nginx:
    image: nginx:1.21.5-alpine
    ports:
      - 8000:80
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
    container_name: web-proxy
    depends_on:
      - frontend
      - backend

  frontend:
    build: ./frontend
    container_name: frontend
    restart: always

  backend:
    build: ./backend
    container_name: backend
    restart: always